version: '3.9'
services:
  db:
    image: postgres:16.2-alpine
    restart: always
    shm_size: 128mb
    hostname: market
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'market'
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - market-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    depends_on:
      - db
    ports:
      - '8000:8000'
    env_file:
      - .env.dev
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    hostname: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'password'

    volumes:
      - rabbit-data:/var/lib/rabbitmq

  sales-worker:
    build:
      context: .
      dockerfile: workers/Dockerfile
    depends_on:
      - rabbitmq
    restart: always
    env_file:
      - .env.dev

volumes:
  rabbit-data:
  market-data: