version: '3.9'
services:
  db:
    image: postgres:16.2-alpine
    restart: always
    shm_size: 128mb
    hostname: market
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: market
    ports:
      - '5432:5432'