"""orders-change

Revision ID: 675422d91d5e
Revises: fa9a6df464fa
Create Date: 2024-06-15 15:43:03.945519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '675422d91d5e'
down_revision: Union[str, None] = 'fa9a6df464fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Orders', sa.Column('order_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Orders', 'order_id')
    # ### end Alembic commands ###
