"""unique-product

Revision ID: b7a16f453347
Revises: b5422d6f82ce
Create Date: 2024-06-10 17:26:34.689574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7a16f453347'
down_revision: Union[str, None] = 'b5422d6f82ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Cart', ['product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Cart', type_='unique')
    # ### end Alembic commands ###
