"""checkout-unique

Revision ID: bb93e3b6b229
Revises: d8024540f19f
Create Date: 2024-06-11 15:23:00.066895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb93e3b6b229'
down_revision: Union[str, None] = 'd8024540f19f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'UserContactInfo', ['product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'UserContactInfo', type_='unique')
    # ### end Alembic commands ###
